#!/usr/bin/env python
import os

Import("env")
Import("env_modules")

module = os.path.splitext(os.path.basename(os.path.realpath(".")))[0]

env_module = env_modules.Clone()

env_module.Append(CPPPATH=[".", "opensteer/include"])


sources = Glob("*.cpp")
sources += Glob("opensteer/src/*.c")
sources += Glob("opensteer/src/*.cpp")
sources += Glob("opensteer/plugins/*.cpp")

# Compile as a static library
lib = env_module.Library(module, sources)
# Add the library as a dependency of the final executable
env.Prepend(LIBS=[lib])
